created global navbar
Young-N-Ambitious/yna_frontend pull request #18
Opened 2022-10-07 11:55 UTC by Chaitanya-087

global navbar created and demo components are updated to closes #8

2022-10-07 11:56 UTC, Chaitanya-087 commented
![image](https://user-images.githubusercontent.com/76115770/194547553-5187799c-38f4-4782-8429-016b90bfff12.png)

2022-10-07 15:01 UTC, anujverma-eng commented
@Chaitanya-087 Kindly check [this](https://github.com/Young-N-Ambitious/yna_frontend/pull/17),
we have already added the Routes here!!
Do make your change in code, accordingly.

2022-10-07 15:55 UTC, Chaitanya-087 commented
@anujverma-eng  updated the folder structure and routes
Thank's for notifying

2022-10-07 16:18 UTC, anujverma-eng requested changes
@Chaitanya-087  I've added a few comments, do check them out.

2022-10-07 16:18 UTC, anujverma-eng commented on src/App.js
> +import {NavBar} from './pages/globalComponents'
@Chaitanya-087 Kindly Import Navbar from './pages' only,
as you can export this NavBar from './pages/index.js'

2022-10-07 16:18 UTC, anujverma-eng commented on src/pages/index.js
> +
use Navbar here as:
import {Navbar} from './globalComponents'

and then export it.

2022-10-08 16:51 UTC, SincerelyBrittany requested changes
The routes were already added. The navbar should only need to import the routes. I would recommend waiting until https://github.com/Young-N-Ambitious/yna_frontend/pull/17 is merged

2022-10-08 17:05 UTC, Chaitanya-087 commented
Okk

2022-10-09 16:35 UTC, Sydnee510 commented
hello @Chaitanya-087 can you resolve merge conflicts so we can go ahead and get this approved

2022-10-09 16:39 UTC, closed without merging

2022-10-14 00:30 UTC, lanicemp commented
Im confused on the status of this PR.  I dont see any files changed.  What are the next steps @Sydnee510 @SincerelyBrittany